[build]
  publish = "public"
  functions = "netlify/functions"

[dev]
  publish = "public"
  functions = "netlify/functions"
  port = 8888

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["openai"]

# 各関数のタイムアウト設定（Pro以上のプランで有効）
[functions.analyze]
  timeout = 10  # デフォルトの10秒